spring:
  servlet:
    multipart:
      max-file-size: 10MB # 文件大小限制
      max-request-size: 100MB # 请求大小限制
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inner-test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 12346
  banner:
    location: banner-custom.txt
  application:
    name: springboot-demo-inner

server:
  port: 8076
  servlet:
    context-path: /
    session:
      timeout: 2592000

xxl:
  job:
    admin:
      # 调度中心服务部署的地址
      addresses: http://127.0.0.1:8081/xxl-job-admin
    # 执行器通讯TOKEN,要和调度中心服务部署配置的accessToken一致，要不然无法连接注册
    accessToken: default_token
    executor:
      # 执行器AppName
      appname: ${spring.application.name}
      # 执行器注册 [选填]：优先使用该配置作为注册地址，为空时使用内嵌服务 ”IP:PORT“ 作为注册地址。从而更灵活的支持容器类型执行器动态IP和动态映射端口问题。
      address:
      ip:
      #执行器端口号：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
      port: 0
      # 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
      logpath:
      # 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
      logretentiondays: 30
