spring:
  servlet:
    multipart:
      max-file-size: 10MB # 文件大小限制
      max-request-size: 100MB # 请求大小限制
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/inner-test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  application:
    name: springDemo

  redis:
    host: localhost
    port: 6379
    password:

server:
  port: 8087
  servlet:
    context-path: /
    session:
      timeout: 2592000

rocketmq:
  name-server: localhost:9876
  producer:
    group: springboot-producer-group
  consumer:
    group: springboot-consumer-group-unique
    topic: springboot-topic



