spring:
  servlet:
    multipart:
      max-file-size: 10MB # 文件大小限制
      max-request-size: 100MB # 请求大小限制
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inner-test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: ENCRYPT(UBHpSHxjL2F8ZiNTJUciZw==)
  # 自定义数据源
#  datasourceCustom:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456
#    pool-size: 30
  banner:
    location: banner-custom.txt
  profiles:
    active: dev
  application:
    name: springDemo

server:
  port: 8087
  servlet:
    context-path: /
    session:
      timeout: 2592000

rpa:
  open: true

# 如果密文加盐，需要配置盐值
#jasypt:
#  encryptor:
#    password: xsy1029*#

# 随机值
my-random:
  secret: "${random.value}"
  number: "${random.int}"
  big-number: "${random.long}"
  uuid: "${random.uuid}"
  number-less-than-ten: "${random.int(10)}"
  number-in-range: "${random.int[1024,65536]}"
  # 集合的表示方法1
  list1:
    - 10
    - 20
    - 30
  # 集合的表示方法2
  list2: [10,20,30]
  # map的表示方式1
  mapinfo:
    name: 张三
    age: 李四
    address:
      province: 江苏省
      city: 南京市
  # 对象
  address:
    province: 江苏省
    city: 南京市
  userList:
    - user:
      name: 张三
      age: 10
    - user:
      name: 李四
      age: 20


# 日志
logging:
  include-application-name: true

# 自定义或多数据源
app:
  datasource:
    first:
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      configuration:
        maximum-pool-size: 30

    second:
      url: jdbc:mysql://localhost:3306/inner-test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      max-total: 30


