spring:
  servlet:
    multipart:
      max-file-size: 10MB # 文件大小限制
      max-request-size: 100MB # 请求大小限制
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: ENC(lL/MjJlfGZmaO2U4U1CMBQ==)
  banner:
    location: banner-custom.txt
  profiles:
    active: test

server:
  port: 8087
  servlet:
    context-path: /
    session:
      timeout: 2592000

rpa:
  open: true

# 如果密文加盐，需要配置盐值
#jasypt:
#  encryptor:
#    password: xsy1029*#

